server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null # 默认忽略null值（使用@EnableWebMvc会失效）
  datasource:
    url: jdbc:mysql://suzumiya-mysql:3306/db_Rinko-Community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: suzumiya-redis
    port: 6379
    password: 123456
  rabbitmq:
    host: suzumiya-rabbitmq
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  elasticsearch:
    uris: http://suzumiya-es:9200
    username: elastic
    password: 123456
  mail:
    host: smtp.qq.com
    port: 25
    username: 3233219183
    password: hvsgdxcoqmssdbfb
    properties:
      smtp.ssl.enable: true # 启用SSL
      smtp.socketFactory.class: SSL_FACTORY # 使用JSSE的SSL
      smtp.socketFactory.fallback: false # 只处理SSL的连接
logging:
  level:
    suzumiya.aspect.ControllerAspect: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
mybatis-plus:
  mapper-locations: suzumiya/mapper
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: suzumiya.model.pojo

ftp:
  ftp_address: suzumiya-ftp
  ftp_port: 21
  ftp_username: ftp
  ftp_password: 123456